version: '3'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_PORT=8080
    ports:
      - "8080:8080"
    entrypoint: ["python", "run.py", "serve"]
